remote_theme: matteogiorgi/matteogiorgi.github.io
plugins:
  - jekyll-seo-tag

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

# file templates for init.sh: not pages of the site
exclude:
  - template/
